/**
 * \file config.h
 *
 * \brief ME30S mbedTLS configuration
 */
/*
 *  Copyright The Mbed TLS Contributors
 *  SPDX-License-Identifier: Apache-2.0
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"); you may
 *  not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

#ifndef MBEDTLS_CONFIG_H
#define MBEDTLS_CONFIG_H

/* Configuration for ME30S
   Generated by Guillermo Garcia Maynez R. April, 2021
*/

/* Newland RTOS custom standard definitions */
//typedef unsigned long size_t;
typedef __SIZE_TYPE__ size_t;
typedef long time_t;
extern void exit(int status);
extern int snprintf(char *str, size_t len, const char *fmt, ...);
extern time_t time(time_t * t);

/* System support */
#define MBEDTLS_HAVE_ASM
#define MBEDTLS_HAVE_TIME

#define MBEDTLS_PLATFORM_C
#define MBEDTLS_PLATFORM_MEMORY
#define MBEDTLS_MEMORY_BUFFER_ALLOC_C
#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#define MBEDTLS_PLATFORM_TIME_ALT
#define MBEDTLS_PLATFORM_SNPRINTF_ALT
#define MBEDTLS_PLATFORM_STD_TIME            time
#define MBEDTLS_PLATFORM_STD_SNPRINTF    snprintf

/* RSA */
#define MBEDTLS_BIGNUM_C
#define MBEDTLS_RSA_C
#define MBEDTLS_PKCS1_V15

/* Ciphers */
#define MBEDTLS_CIPHER_C
#define MBEDTLS_DES_C

/* Hashes */
#define MBEDTLS_MD_C
#define MBEDTLS_SHA256_C

/* Misc */
#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_HMAC_DRBG_C
#define MBEDTLS_OID_C
#define MBEDTLS_VERSION_C

#include "mbedtls/check_config.h"

#endif /* MBEDTLS_CONFIG_H */
